# Generated by Django 3.1.7 on 2021-02-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('acronymn', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Project Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Logo Image')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform_id', models.CharField(default='default_id', max_length=20, verbose_name='Identifier')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Platform Website')),
                ('parent_platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdatasystem.platform')),
            ],
            options={
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='DataSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='TmpName')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.platform', verbose_name='Project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'DataSystem',
                'verbose_name_plural': 'DataSystems',
            },
        ),
    ]
