# Generated by Django 3.1.7 on 2021-02-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0002_auto_20210226_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasystem',
            options={'verbose_name': 'Data System', 'verbose_name_plural': 'Data Systems'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'Platform', 'verbose_name_plural': 'Platforms'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='samplingsystem',
            options={'verbose_name': 'Sampling System', 'verbose_name_plural': 'Sampling Systems'},
        ),
        migrations.AlterModelOptions(
            name='samplingsystemlocation',
            options={'verbose_name': 'Sampling Location', 'verbose_name_plural': 'Sampling Locations'},
        ),
        migrations.AlterModelOptions(
            name='samplingsystemsamplepoint',
            options={'verbose_name': 'Sample Point', 'verbose_name_plural': 'Sample Points'},
        ),
        migrations.AlterField(
            model_name='datasystem',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasystems', to='envdatasystem.platform', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='datasystem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasystems', to='envdatasystem.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='parent_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platforms', to='envdatasystem.platform'),
        ),
        migrations.AlterField(
            model_name='samplingsystem',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='samplingsystems', to='envdatasystem.SamplingSystemLocation', verbose_name='sampling Locations'),
        ),
        migrations.AlterField(
            model_name='samplingsystem',
            name='sample_points',
            field=models.ManyToManyField(blank=True, related_name='samplingsystems', to='envdatasystem.SamplingSystemSamplePoint', verbose_name='Sampling Points'),
        ),
        migrations.AlterField(
            model_name='samplingsystemlocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplelocations', to='envdatasystem.samplingsystemlocation', verbose_name='Parent Location'),
        ),
        migrations.AlterField(
            model_name='samplingsystemlocation',
            name='sampling_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplelocations', to='envdatasystem.samplingsystem', verbose_name='Sampling System'),
        ),
        migrations.AlterField(
            model_name='samplingsystemsamplepoint',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplepoints', to='envdatasystem.samplingsystemsamplepoint', verbose_name='Parent Sampling Point'),
        ),
        migrations.AlterField(
            model_name='samplingsystemsamplepoint',
            name='sampling_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samplepoints', to='envdatasystem.samplingsystem', verbose_name='Sample System'),
        ),
    ]
