# Generated by Django 3.1.7 on 2021-02-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0003_auto_20210226_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingsystemlocation',
            name='sampling_system',
        ),
        migrations.RemoveField(
            model_name='samplingsystemsamplepoint',
            name='sampling_system',
        ),
    ]
