# Generated by Django 3.1.7 on 2021-02-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0006_controllerdef_component_map'),
        ('envdatasystem', '0005_controllersystem_daqsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ComponentMap',
                'verbose_name_plural': 'ComponentMaps',
            },
        ),
        migrations.CreateModel(
            name='ControllerComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ControllerComponent',
                'verbose_name_plural': 'ControllerComponents',
            },
        ),
        migrations.CreateModel(
            name='InstrumentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ControllerComponent',
                'verbose_name_plural': 'ControllerComponents',
            },
        ),
        migrations.AddField(
            model_name='controllersystem',
            name='daq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllersystem_daq', to='envdatasystem.daqsystem', verbose_name='DAQ System'),
        ),
        migrations.AddField(
            model_name='controllersystem',
            name='parent_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllersystem_parentcontroller', to='envdatasystem.controllersystem', verbose_name='Parent Controller'),
        ),
        migrations.AlterField(
            model_name='controllersystem',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllersystem_controller', to='envdaq.controller', verbose_name='Controller'),
        ),
        migrations.CreateModel(
            name='InstrumentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentsystem_controller', to='envdatasystem.controllersystem', verbose_name='Controller System')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentsystem_instrument', to='envdaq.instrumentalias', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'Instrument System',
                'verbose_name_plural': 'Instrument Systems',
            },
        ),
        migrations.CreateModel(
            name='InstrumentComponentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Component')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentcomponentitem_component', to='envdatasystem.instrumentcomponent', verbose_name='Component')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentcomponentitem_controller', to='envdatasystem.instrumentsystem', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'instrumentcomponentitem',
                'verbose_name_plural': 'instrumentcomponentitems',
            },
        ),
        migrations.AddField(
            model_name='instrumentcomponent',
            name='Instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentcomponent_instrument', to='envdatasystem.instrumentsystem', verbose_name='Controller'),
        ),
        migrations.CreateModel(
            name='ControllerComponentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Component')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentitem_component', to='envdatasystem.controllercomponent', verbose_name='Component')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentitem_controller', to='envdatasystem.controllersystem', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'controllercomponentitem',
                'verbose_name_plural': 'controllercomponentitems',
            },
        ),
        migrations.AddField(
            model_name='controllercomponent',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponent_controller', to='envdatasystem.controllersystem', verbose_name='Controller'),
        ),
    ]
