# Generated by Django 3.1.7 on 2021-02-27 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0001_initial'),
        ('envdatasystem', '0006_auto_20210227_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComponentMap',
        ),
        migrations.AlterModelOptions(
            name='instrumentcomponent',
            options={'verbose_name': 'InstrumentComponent', 'verbose_name_plural': 'InstrumentComponents'},
        ),
        migrations.AddField(
            model_name='controllersystem',
            name='prefix',
            field=models.CharField(default='default', max_length=10, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='instrumentsystem',
            name='prefix',
            field=models.CharField(default='default', max_length=10, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='instrumentsystem',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentsystem_instrument', to='envinventory.instrument', verbose_name='Instrument'),
        ),
    ]
