# Generated by Django 3.1.7 on 2021-02-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0007_auto_20210227_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerComponentController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Component')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentcontroller_component', to='envdatasystem.controllercomponent', verbose_name='Component')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentcontroller_controller', to='envdatasystem.controllersystem', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'controllercomponentcontroller',
                'verbose_name_plural': 'controllercomponentcontrollers',
            },
        ),
        migrations.CreateModel(
            name='ControllerComponentInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Component')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentinstrument_component', to='envdatasystem.controllercomponent', verbose_name='Component')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentinstrument_controller', to='envdatasystem.controllersystem', verbose_name='Controller')),
            ],
            options={
                'verbose_name': 'controllercomponentinstrument',
                'verbose_name_plural': 'controllercomponentinstruments',
            },
        ),
        migrations.DeleteModel(
            name='ControllerComponentItem',
        ),
    ]
