# Generated by Django 3.1.7 on 2021-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0008_auto_20210227_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllercomponentcontroller',
            options={'verbose_name': 'ControllerComponent Controller', 'verbose_name_plural': 'ControllerComponent Controllers'},
        ),
        migrations.AlterModelOptions(
            name='controllercomponentinstrument',
            options={'verbose_name': 'ControllerComponent Instrument', 'verbose_name_plural': 'ControllerComponent Instruments'},
        ),
        migrations.AddField(
            model_name='controllercomponent',
            name='type',
            field=models.CharField(choices=[('controller', 'Controller'), ('instrument', 'Instrument')], default='instrument', max_length=50, verbose_name='Type'),
        ),
    ]
