# Generated by Django 3.1.7 on 2021-02-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0009_auto_20210227_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentComponentInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary Component')),
            ],
            options={
                'verbose_name': 'InstrumentComponent Interface',
                'verbose_name_plural': 'InstrumentComponent Interfaces',
            },
        ),
        migrations.AddField(
            model_name='instrumentcomponent',
            name='type',
            field=models.CharField(choices=[('interface', 'Interface')], default='interface', max_length=50, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='InstrumentComponentItem',
        ),
        migrations.AddField(
            model_name='instrumentcomponentinterface',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentcomponentinterface_component', to='envdatasystem.instrumentcomponent', verbose_name='Component'),
        ),
        migrations.AddField(
            model_name='instrumentcomponentinterface',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentcomponentinterface_controller', to='envdatasystem.instrumentsystem', verbose_name='Controller'),
        ),
    ]
