# Generated by Django 3.1.7 on 2021-02-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0011_auto_20210227_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllercomponentinstrument',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllercomponentinstrument_instrument', to='envdatasystem.instrumentsystem', verbose_name='Instrument'),
        ),
    ]
