# Generated by Django 3.1.7 on 2021-02-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0013_remove_controllercomponentinstrument_instrument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControllerComponentInstrument',
        ),
    ]
