# Generated by Django 3.1.7 on 2021-02-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0016_auto_20210228_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platformlocation_parents', to='envdatasystem.platformlocation', verbose_name='Parent Location')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformlocation_platforms', to='envdatasystem.platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'platformlocation',
                'verbose_name_plural': 'platformlocations',
            },
        ),
    ]
