# Generated by Django 3.1.7 on 2021-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0018_auto_20210228_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasystem',
            name='sampling_system',
            field=models.ManyToManyField(blank=True, to='envdatasystem.SamplingSystemMap', verbose_name='Sampling System'),
        ),
    ]
