# Generated by Django 3.1.7 on 2021-02-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0019_datasystem_sampling_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSMInstrumentMap',
        ),
    ]
