# Generated by Django 3.1.7 on 2021-02-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0006_controllerdef_component_map'),
        ('envdatasystem', '0020_delete_ssminstrumentmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSMInstrumentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.instrumentalias', verbose_name='Instrument')),
                ('ss_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystemlocation', verbose_name='SS Location')),
                ('ss_sample_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystemsamplepoint', verbose_name='SS Location')),
                ('system_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystemmap', verbose_name='System Map')),
            ],
            options={
                'verbose_name': 'SSMInstrumentMap',
                'verbose_name_plural': 'SSMInstrumentMaps',
            },
        ),
    ]
