# Generated by Django 3.1.7 on 2021-02-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0021_ssminstrumentmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssminstrumentmap',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.instrumentsystem', verbose_name='Instrument'),
        ),
    ]
