# Generated by Django 3.1.7 on 2021-02-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0023_auto_20210228_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformlocation',
            options={'verbose_name': 'Platform Location', 'verbose_name_plural': 'Platform Locations'},
        ),
    ]
