# Generated by Django 3.1.7 on 2021-02-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0024_auto_20210228_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplingsystemlocation',
            options={'verbose_name': 'SS Sampling Location', 'verbose_name_plural': 'SS Sampling Locations'},
        ),
        migrations.AlterModelOptions(
            name='samplingsystemsamplepoint',
            options={'verbose_name': 'SS Sampling Point', 'verbose_name_plural': 'SS Sampling Points'},
        ),
        migrations.AlterField(
            model_name='ssminstrumentmap',
            name='ss_sample_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystemsamplepoint', verbose_name='SS Sampling Point'),
        ),
    ]
