# Generated by Django 3.1.7 on 2021-02-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0025_auto_20210228_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformlocation',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformlocations', to='envdatasystem.platform', verbose_name='Platform'),
        ),
    ]
