# Generated by Django 3.1.7 on 2021-02-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0026_auto_20210228_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcomponent',
            name='Instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.instrumentsystem', verbose_name='Controller'),
        ),
        migrations.AlterField(
            model_name='instrumentcomponentinterface',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.instrumentcomponent', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='platformlocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platformlocations_parent', to='envdatasystem.platformlocation', verbose_name='Parent Location'),
        ),
    ]
