# Generated by Django 3.1.7 on 2021-04-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0013_auto_20210421_1725'),
        ('envdatasystem', '0027_auto_20210228_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcomponent',
            name='Instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.instrumentsystem', verbose_name='Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentcomponent',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='instrumentcomponentinterface',
            name='interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.interface', verbose_name='Interface'),
        ),
    ]
