# Generated by Django 3.1.7 on 2021-04-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0028_auto_20210421_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasystem',
            name='name',
            field=models.CharField(default='default', max_length=50, verbose_name='Name'),
        ),
    ]
