# Generated by Django 3.2.3 on 2021-07-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0029_auto_20210421_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasystem',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='datasystem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='datasystem',
            name='sampling_system',
        ),
        migrations.AddField(
            model_name='datasystem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='datasystem',
            name='name_id',
            field=models.CharField(blank=True, help_text='Shortened version of name for use in id strings', max_length=20, null=True, verbose_name='Name ID'),
        ),
    ]
