# Generated by Django 3.2.3 on 2021-07-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0031_auto_20210712_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasystem',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasystems_platform', to='envdatasystem.platform', verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='datasystem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasystems_project', to='envdatasystem.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('AIRCRAFT', 'Aircraft'), ('SHIP', 'Ship'), ('UAS', 'UAS'), ('STATION', 'Station/Lab')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
