# Generated by Django 3.2.3 on 2021-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0032_auto_20210712_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasystem',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='datasystem',
            name='project',
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring'), ('UAS', 'UAS'), ('STATION', 'Station/Lab'), ('SHIP', 'Ship')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
