# Generated by Django 3.2.3 on 2021-07-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0034_auto_20210712_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasystem',
            name='projects',
            field=models.ManyToManyField(null=True, to='envdatasystem.Project', verbose_name='Project List'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
