# Generated by Django 3.2.3 on 2021-07-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0038_auto_20210714_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.platformevent', verbose_name='Parent Event'),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.projectevent', verbose_name='Parent Event'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
