# Generated by Django 3.2.3 on 2021-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0039_auto_20210714_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformevent',
            options={'verbose_name': 'Platform Event', 'verbose_name_plural': 'Platform Events'},
        ),
        migrations.AlterModelOptions(
            name='projectevent',
            options={'verbose_name': 'Project Event', 'verbose_name_plural': 'Project Events'},
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring'), ('SHIP', 'Ship'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
