# Generated by Django 3.2.3 on 2021-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0040_auto_20210714_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AddConstraint(
            model_name='platformevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('platform__isnull', False), ('parent__isnull', True)), models.Q(('platform__isnull', True), ('parent__isnull', False)), _connector='OR'), name='oaoo_platform_parent_event'),
        ),
        migrations.AddConstraint(
            model_name='projectevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project__isnull', False), ('parent__isnull', True)), models.Q(('project__isnull', True), ('parent__isnull', False)), _connector='OR'), name='oaoo_project_parent_event'),
        ),
    ]
