# Generated by Django 3.2.3 on 2021-07-14 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0041_auto_20210714_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AlterField(
            model_name='platformevent',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.platform', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.project', verbose_name='Project'),
        ),
    ]
