# Generated by Django 3.2.3 on 2021-07-15 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0042_auto_20210714_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('STATION', 'Station/Lab'), ('AIRCRAFT', 'Aircraft'), ('SHIP', 'Ship'), ('UAS', 'UAS'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='SamplePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.platformevent', verbose_name='Platform Event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.project', verbose_name='Project')),
                ('sampling_systems', models.ManyToManyField(to='envdatasystem.SamplingSystem', verbose_name='Sampling System(s)')),
            ],
            options={
                'verbose_name': 'SamplePeriod',
                'verbose_name_plural': 'SamplePeriods',
            },
        ),
    ]
