# Generated by Django 3.2.3 on 2021-07-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0045_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
