# Generated by Django 3.2.3 on 2021-07-16 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0048_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplingsystem',
            managers=[
                ('version', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='samplingsystem',
            name='valid_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Start Time'),
        ),
        migrations.AddField(
            model_name='samplingsystem',
            name='valid_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid Start Time'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('STATION', 'Station/Lab'), ('SHIP', 'Ship'), ('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='PlatformLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('long_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platformlocations_parent', to='envdatasystem.platformlocation', verbose_name='Parent Location')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformlocations', to='envdatasystem.platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Platform Location',
                'verbose_name_plural': 'Platform Locations',
            },
        ),
    ]
