# Generated by Django 3.2.3 on 2021-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0049_auto_20210716_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('STATION', 'Station/Lab'), ('SHIP', 'Ship'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
