# Generated by Django 3.2.3 on 2021-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0050_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
