# Generated by Django 3.2.3 on 2021-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0053_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('UAS', 'UAS'), ('SHIP', 'Ship')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
