# Generated by Django 3.2.3 on 2021-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0054_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplingsystem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('UAS', 'UAS'), ('SHIP', 'Ship'), ('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('AIRCRAFT', 'Aircraft')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
