# Generated by Django 3.2.3 on 2021-07-17 15:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0055_auto_20210717_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplingsystem',
            managers=[
                ('version', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('UAS', 'UAS'), ('SHIP', 'Ship'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
