# Generated by Django 3.2.3 on 2021-07-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0056_auto_20210717_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='samplingsystem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
