# Generated by Django 3.2.3 on 2021-07-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0057_auto_20210717_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplingsystem',
            old_name='valid_start',
            new_name='version_starttime',
        ),
        migrations.RenameField(
            model_name='samplingsystem',
            old_name='valid_stop',
            new_name='version_stoptime',
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('AIRCRAFT', 'Aircraft'), ('STATION', 'Station/Lab'), ('UAS', 'UAS'), ('SHIP', 'Ship')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
