# Generated by Django 3.2.3 on 2021-07-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0058_auto_20210717_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('SHIP', 'Ship'), ('STATION', 'Station/Lab')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='DAQDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.platformevent', verbose_name='Platform Event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdatasystem.project', verbose_name='Project')),
                ('sampling_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystem', verbose_name='Sampling System')),
            ],
            options={
                'verbose_name': 'DAQDataset',
                'verbose_name_plural': 'DAQDatasets',
            },
        ),
    ]
