# Generated by Django 3.2.3 on 2021-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0059_auto_20210717_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqdataset',
            name='version_starttime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Version Start Time'),
        ),
        migrations.AddField(
            model_name='daqdataset',
            name='version_stoptime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Version Stop Time'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('STATION', 'Station/Lab'), ('SHIP', 'Ship'), ('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
