# Generated by Django 3.2.3 on 2021-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0061_auto_20210717_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplingsystemdataset',
            options={'verbose_name': 'SamplingSystem Dataset', 'verbose_name_plural': 'SamplingSystem Datasets'},
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('SHIP', 'Ship'), ('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AddConstraint(
            model_name='samplingsystemlocation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sampling_system__isnull', False), ('parent__isnull', True)), models.Q(('sampling_system__isnull', True), ('parent__isnull', False)), _connector='OR'), name='oaoo_sampling_system_location'),
        ),
        migrations.AddConstraint(
            model_name='samplingsystemsamplepoint',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sampling_system__isnull', False), ('parent__isnull', True)), models.Q(('sampling_system__isnull', True), ('parent__isnull', False)), _connector='OR'), name='oaoo_sampling_system_sample_point'),
        ),
    ]
