# Generated by Django 3.2.3 on 2021-07-18 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0039_auto_20210528_2019'),
        ('envdatasystem', '0062_auto_20210717_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('UAS', 'UAS'), ('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('SHIP', 'Ship')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='SamplingSystemInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqinstrument', verbose_name='Instrument')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdatasystem.samplingsystemlocation', verbose_name='Location')),
                ('sample_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdatasystem.samplingsystemsamplepoint', verbose_name='Sample Point')),
                ('sampling_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystem', verbose_name='Sampling System')),
            ],
            options={
                'verbose_name': 'SamplingSystemInstrument',
                'verbose_name_plural': 'SamplingSystemInstruments',
            },
        ),
        migrations.CreateModel(
            name='SamplingSystemController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Controller')),
                ('sampling_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.samplingsystem', verbose_name='Sampling System')),
            ],
            options={
                'verbose_name': 'SamplingSystemController',
                'verbose_name_plural': 'SamplingSystemControllers',
            },
        ),
    ]
