# Generated by Django 3.2.3 on 2021-07-18 18:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0002_auto_20210122_2145'),
        ('envdatasystem', '0063_auto_20210718_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('STATION', 'Station/Lab'), ('AIRCRAFT', 'Aircraft'), ('SHIP', 'Ship'), ('MOORING', 'Mooring'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.CreateModel(
            name='SSDatasetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event Type')),
                ('eventID', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('start_datetime', models.DateTimeField(verbose_name='Start DateTime')),
                ('stop_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Stop DateTime')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdatasystem.samplingsystemdataset', verbose_name='Dataset')),
                ('tags', models.ManyToManyField(blank=True, to='envtags.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'SSDatasetEvent',
                'verbose_name_plural': 'SSDatasetEvents',
            },
        ),
    ]
