# Generated by Django 3.2.3 on 2021-07-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0065_auto_20210718_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssdatasetevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdatasystem.ssdatasetevent', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('SHIP', 'Ship'), ('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AddConstraint(
            model_name='ssdatasetevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dataset__isnull', False), ('parent__isnull', True)), models.Q(('dataset__isnull', True), ('parent__isnull', False)), _connector='OR'), name='oaoo_ss_dataset_event'),
        ),
    ]
