# Generated by Django 3.2.3 on 2021-07-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0067_alter_platform_platform_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplingsystemdataset',
            name='version_starttime',
        ),
        migrations.RemoveField(
            model_name='samplingsystemdataset',
            name='version_stoptime',
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('MOORING', 'Mooring'), ('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AlterField(
            model_name='platformevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_event', to='envdatasystem.platformevent', verbose_name='Parent Event'),
        ),
        migrations.AlterField(
            model_name='projectevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_project', to='envdatasystem.projectevent', verbose_name='Parent Event'),
        ),
    ]
