# Generated by Django 3.2.3 on 2021-07-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0068_auto_20210721_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('SHIP', 'Ship'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AlterField(
            model_name='ssdatasetevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_dataset', to='envdatasystem.ssdatasetevent', verbose_name='Parent'),
        ),
    ]
