# Generated by Django 3.2.3 on 2021-07-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0069_auto_20210721_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS'), ('STATION', 'Station/Lab'), ('MOORING', 'Mooring'), ('SHIP', 'Ship')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
        migrations.AlterField(
            model_name='platformevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_events', to='envdatasystem.platformevent', verbose_name='Parent Event'),
        ),
    ]
