# Generated by Django 3.2.3 on 2021-07-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdatasystem', '0070_auto_20210721_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('SHIP', 'Ship'), ('MOORING', 'Mooring'), ('STATION', 'Station/Lab'), ('AIRCRAFT', 'Aircraft'), ('UAS', 'UAS')], default='STATION', max_length=10, verbose_name='Platform Type'),
        ),
    ]
