# Generated by Django 3.1.5 on 2021-02-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AddField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='network',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created'),
        ),
    ]
