# Generated by Django 3.1.5 on 2021-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0002_auto_20210218_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='network',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='network',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
    ]
