# Generated by Django 3.1.5 on 2021-02-19 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0003_auto_20210218_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAQRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_service', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=100, verbose_name='Host name')),
                ('port', models.IntegerField(verbose_name='Port number')),
                ('regkey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('daq_list', models.TextField(verbose_name='DAQ List')),
                ('daq_type', models.CharField(default='DAQServer', max_length=50, verbose_name='Type')),
                ('config', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='CONNECTED', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'DAQ List',
                'verbose_name_plural': 'DAQ Lists',
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_service', models.BooleanField(default=True)),
                ('host', models.CharField(max_length=100, verbose_name='Host name')),
                ('port', models.IntegerField(verbose_name='Port number')),
                ('regkey', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('service_list', models.TextField(verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Service Registration',
                'verbose_name_plural': 'Service Registrations',
            },
        ),
    ]
