# Generated by Django 3.1.5 on 2021-02-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0004_daqregistration_serviceregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqregistration',
            name='daq_list',
        ),
    ]
