# Generated by Django 3.1.5 on 2021-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0005_remove_daqregistration_daq_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistration',
            name='service_list',
            field=models.TextField(default='{}', verbose_name='Services'),
        ),
    ]
