# Generated by Django 3.1.7 on 2021-02-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0007_network_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daqregistration',
            options={'verbose_name': 'DAQ Registration', 'verbose_name_plural': 'DAQ Registrations'},
        ),
    ]
