# Generated by Django 3.1.7 on 2021-02-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0009_network_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='registrations',
        ),
    ]
