# Generated by Django 3.1.7 on 2021-02-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0012_serviceregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqregistration',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='serviceregistration',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
    ]
