# Generated by Django 3.1.7 on 2021-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0013_auto_20210221_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqregistration',
            name='host',
        ),
        migrations.RemoveField(
            model_name='daqregistration',
            name='local_service',
        ),
        migrations.RemoveField(
            model_name='daqregistration',
            name='port',
        ),
        migrations.AddField(
            model_name='daqregistration',
            name='namespace',
            field=models.CharField(default='default', max_length=50, verbose_name='Namespace'),
        ),
    ]
