# Generated by Django 3.1.7 on 2021-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0014_auto_20210222_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqregistration',
            name='namespace',
            field=models.CharField(default='default', max_length=100, verbose_name='Namespace'),
        ),
    ]
