# Generated by Django 3.1.7 on 2021-04-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0015_auto_20210223_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqregistration',
            name='config2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
