# Generated by Django 3.1.7 on 2021-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0017_auto_20210415_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqregistration',
            name='reg_id',
            field=models.CharField(default='default', max_length=100, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daqregistration',
            name='config2',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='daqregistration',
            name='namespace',
            field=models.JSONField(blank=True, default=dict, verbose_name='Namespace'),
        ),
    ]
