# Generated by Django 3.1.7 on 2021-04-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0018_auto_20210426_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqregistration',
            name='status2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Status(JSON)'),
        ),
    ]
