# Generated by Django 3.1.7 on 2021-04-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0019_daqregistration_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqregistration',
            name='status2',
        ),
    ]
