# Generated by Django 3.1.7 on 2021-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0020_remove_daqregistration_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqregistration',
            name='reg_id2',
            field=models.JSONField(default=dict, verbose_name='ID_JSON'),
        ),
    ]
