# Generated by Django 3.1.7 on 2021-05-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0021_daqregistration_reg_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqregistration',
            name='config',
        ),
        migrations.RemoveField(
            model_name='daqregistration',
            name='config2',
        ),
        migrations.RemoveField(
            model_name='daqregistration',
            name='reg_id',
        ),
        migrations.AlterField(
            model_name='daqregistration',
            name='status',
            field=models.CharField(default='UNKNOWN', max_length=50, verbose_name='Status'),
        ),
    ]
