# Generated by Django 3.1.7 on 2021-05-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0022_auto_20210526_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqregistration',
            name='reg_id2',
        ),
        migrations.AddField(
            model_name='daqregistration',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='daqregistration',
            name='reg_id',
            field=models.JSONField(default=dict, verbose_name='Reg ID'),
        ),
        migrations.AddField(
            model_name='daqregistration',
            name='status2',
            field=models.JSONField(blank=True, default=dict, verbose_name='Status_JSON'),
        ),
    ]
