# Generated by Django 3.1.7 on 2021-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envnet', '0023_auto_20210526_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqregistration',
            name='daq_type',
            field=models.CharField(default='daqserver', max_length=50, verbose_name='Type'),
        ),
    ]
