# Generated by Django 2.2.1 on 2019-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envtags', '0002_tag_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_dim', models.BooleanField(default=False)),
                ('unlimited_dim', models.BooleanField(default=False)),
                ('length', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VariableDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.CharField(max_length=20, null=True)),
                ('source_type', models.CharField(max_length=30, null=True)),
                ('data_type', models.CharField(choices=[('NUMERIC', 'NUMERIC'), ('TEXT', 'TEXT')], default='NUMERIC', max_length=7)),
                ('tags', models.ManyToManyField(blank=True, related_name='variable_tags', to='envtags.Tag')),
            ],
        ),
    ]
