# Generated by Django 2.2.1 on 2019-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiondef',
            name='units',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
