# Generated by Django 2.1.5 on 2019-02-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('length', models.CharField(blank=True, help_text='Enter dimensional length (m)', max_length=20, null=True)),
                ('width', models.CharField(blank=True, help_text='Enter dimensional width (m)', max_length=20, null=True)),
                ('height', models.CharField(blank=True, help_text='Enter dimensional height (m)', max_length=20, null=True)),
                ('weight', models.CharField(blank=True, help_text='Enter weight (kg)', max_length=20, null=True)),
                ('value', models.CharField(blank=True, help_text='Enter value (USD)', max_length=20, null=True)),
                ('model', models.CharField(help_text='Instrument type name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
