# Generated by Django 2.1.5 on 2019-02-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='long_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
