# Generated by Django 2.1.5 on 2019-02-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envcontacts', '0008_auto_20190219_0233'),
        ('envinventory', '0002_auto_20190219_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='mfg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envcontacts.Organization'),
        ),
    ]
