# Generated by Django 2.1.5 on 2019-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0003_instrumentdef_mfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='_class',
            field=models.CharField(blank=True, help_text='Enter class name', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='_module',
            field=models.CharField(blank=True, help_text='Enter module name', max_length=100, null=True),
        ),
    ]
