# Generated by Django 2.1.5 on 2019-02-19 02:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0004_auto_20190219_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=50, null=True)),
                ('uniqueID', models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True)),
                ('serial_number', models.CharField(blank=True, default='NA', help_text='Enter serial number', max_length=30, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('ON_LOAN', 'Out on loan'), ('MAINTENANCE', 'Out for maintenance')], default='MAINTENANCE', max_length=20)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envinventory.InstrumentDef')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
