# Generated by Django 2.1.5 on 2019-02-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envcontacts', '0013_auto_20190219_1610'),
        ('envinventory', '0005_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='envcontacts.Person'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envcontacts.Organization'),
        ),
    ]
