# Generated by Django 2.1.5 on 2019-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0006_auto_20190219_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='envcontacts.Person'),
        ),
    ]
