# Generated by Django 2.1.5 on 2019-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0001_initial'),
        ('envinventory', '0007_auto_20190219_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='tags',
            field=models.ManyToManyField(blank=True, to='envtags.Tag'),
        ),
    ]
