# Generated by Django 2.1.5 on 2019-02-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0002_tag_type'),
        ('envinventory', '0008_instrumentdef_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'INSTRUMENT_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inst_type', to='envtags.Tag'),
        ),
        migrations.AlterField(
            model_name='instrumentdef',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='inv_tags', to='envtags.Tag'),
        ),
    ]
