# Generated by Django 2.1.5 on 2019-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0009_auto_20190219_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentdef',
            options={'verbose_name': 'Instrument Definition', 'verbose_name_plural': 'Instrument Definitions '},
        ),
        migrations.AlterField(
            model_name='instrumentdef',
            name='model',
            field=models.CharField(help_text='Instrument model', max_length=50),
        ),
    ]
