# Generated by Django 2.2.1 on 2019-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0010_auto_20190219_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentdef',
            name='data_type',
            field=models.CharField(choices=[('NUMERIC', 'NUMERIC'), ('TEXT', 'TEXT')], default='NUMERIC', max_length=7),
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='source_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='units',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
