# Generated by Django 2.2.1 on 2019-08-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0011_auto_20190718_1932'),
        ('envinventory', '0011_auto_20190810_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentdef',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='instrumentdef',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='instrumentdef',
            name='units',
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='measurement_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.Configuration'),
        ),
    ]
