# Generated by Django 2.2.1 on 2020-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo Image'),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Project Website'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
