# Generated by Django 2.2.1 on 2020-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0005_auto_20200327_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='event_type',
            field=models.CharField(default='PROJECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Short Name / Acronym'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(blank=True, verbose_name='Start DateTime'),
        ),
    ]
