# Generated by Django 2.2.1 on 2020-03-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0007_auto_20200327_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='event_type',
        ),
    ]
