# Generated by Django 2.2.1 on 2020-03-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0008_remove_project_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start DateTime'),
        ),
    ]
