# Generated by Django 2.2.1 on 2020-03-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0009_auto_20200327_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='envproject_project_related', related_query_name='envproject_projects', to='envtags.Tag'),
        ),
    ]
