# Generated by Django 2.2.1 on 2020-03-27 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0010_auto_20200327_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start DateTime'),
        ),
    ]
