# Generated by Django 2.2.1 on 2020-03-31 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0013_auto_20200327_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectplatformevent',
            name='platform',
        ),
        migrations.AddField(
            model_name='platform',
            name='parent_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envproject.Platform'),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_id',
            field=models.CharField(default='default_id', max_length=20, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='project',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='project_platforms', to='envproject.Platform'),
        ),
        migrations.AddField(
            model_name='projectplatformevent',
            name='platforms',
            field=models.ManyToManyField(related_name='projectplatformevent_platforms', to='envproject.Platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='long_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
