# Generated by Django 2.2.1 on 2020-03-31 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envproject', '0014_auto_20200331_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplatformevent',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='projectplatformevent_platforms', to='envproject.Platform'),
        ),
    ]
