# Generated by Django 2.1.5 on 2019-02-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
