# Generated by Django 2.1.5 on 2019-02-15 23:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name for this controller', max_length=30)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Controller type name', max_length=30)),
                ('_class', models.CharField(help_text='Enter class name', max_length=30)),
                ('_module', models.CharField(help_text='Enter module name', max_length=50)),
                ('test', models.CharField(help_text='Enter test name', max_length=50)),
            ],
            options={
                'verbose_name': 'Controller Definition',
                'verbose_name_plural': 'Controller Definition',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=None, max_length=30, null=True)),
                ('uniqueID', models.UUIDField(blank=True, default=uuid.uuid1, editable=False, null=True)),
                ('serial_number', models.CharField(blank=True, default='NA', help_text='Enter serial number', max_length=30, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('ON_LOAN', 'Out on loan'), ('MAINTENANCE', 'Out for maintenance')], default='MAINTENANCE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', help_text='Enter ', max_length=50)),
                ('model', models.CharField(help_text='Instrument type name', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentMask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name that describes what the instrument represents', max_length=30)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='envdaq.Controller')),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.InstrumentDef'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument', to='envdaq.InstrumentMask'),
        ),
        migrations.AddField(
            model_name='controller',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='envdaq.ControllerDef'),
        ),
    ]
