# Generated by Django 2.2.1 on 2019-08-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentalias',
            name='label',
            field=models.CharField(help_text='Label for plots, tables, etc. A more pleasing version of name. Defaults to name if left blank', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentalias',
            name='name',
            field=models.CharField(help_text='Enter the name that describes what the instrument represents and can be used as header text (i.e., no spaces)', max_length=30),
        ),
    ]
