# Generated by Django 2.2.1 on 2019-08-12 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0002_auto_20190812_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentalias',
            options={'verbose_name': 'Instrument Alias', 'verbose_name_plural': 'Instrument Aliases'},
        ),
    ]
