# Generated by Django 2.2.1 on 2019-10-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0001_initial'),
        ('envdaq', '0003_auto_20190812_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='measurement_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envtags.Configuration'),
        ),
    ]
