# Generated by Django 2.2.1 on 2019-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0004_controller_measurement_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='alias_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
