# Generated by Django 3.1.7 on 2021-02-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0005_controller_alias_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllerdef',
            name='component_map',
            field=models.TextField(default='{}', verbose_name='Component Map'),
        ),
    ]
