# Generated by Django 2.1.5 on 2019-02-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0006_auto_20190219_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllerdef',
            options={'verbose_name': 'Controller Definition', 'verbose_name_plural': 'Controller Definitions'},
        ),
    ]
