# Generated by Django 3.1.7 on 2021-04-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0002_auto_20210122_2145'),
        ('envdaq', '0006_controllerdef_component_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Interface type name', max_length=30)),
                ('_class', models.CharField(help_text='Enter class name', max_length=30)),
                ('_module', models.CharField(help_text='Enter module name', max_length=50)),
                ('type', models.CharField(choices=[('SerialPort', 'Serial'), ('TCPPort', 'TCP'), ('I2C', 'I2C'), ('A2D', 'A/D'), ('D2A', 'D/A')], default='TCPPort', max_length=15)),
                ('tags', models.ManyToManyField(blank=True, related_name='interfacedef_tags', to='envtags.Tag')),
            ],
            options={
                'verbose_name': 'Interface Definition',
                'verbose_name_plural': 'Interface Definitions',
            },
        ),
    ]
