# Generated by Django 2.2.1 on 2019-07-09 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0010_auto_20190219_2034'),
        ('envdaq', '0007_auto_20190219_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentmask',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='envinventory.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentmask',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='envdaq.Controller'),
        ),
    ]
