# Generated by Django 3.1.7 on 2021-04-15 22:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envtags', '0002_auto_20210122_2145'),
        ('envdaq', '0007_interfacedef'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('host_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Host Name')),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Host IP')),
                ('config', models.JSONField(default=None, verbose_name='Configuration')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='envdaq.interfacedef')),
                ('tags', models.ManyToManyField(blank=True, related_name='interface_tags', to='envtags.Tag')),
            ],
            options={
                'verbose_name_plural': 'Interfaces',
            },
        ),
    ]
