# Generated by Django 2.2.1 on 2019-07-17 23:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0008_auto_20190709_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('config', models.TextField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='test', max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='test', max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='controller',
            options={'verbose_name_plural': 'Controllers'},
        ),
        migrations.AlterField(
            model_name='controller',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='DAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('host', models.CharField(max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('port', models.IntegerField(null=True)),
                ('configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='envdaq.Configuration')),
            ],
            options={
                'verbose_name': 'DAQ Server',
                'verbose_name_plural': 'DAQ Servers',
            },
        ),
    ]
