# Generated by Django 3.1.7 on 2021-04-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0008_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='config',
            field=models.JSONField(default=dict, verbose_name='Configuration'),
        ),
    ]
