# Generated by Django 3.1.7 on 2021-04-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0009_auto_20210415_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
    ]
