# Generated by Django 2.2.1 on 2019-07-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0009_auto_20190717_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='config',
            field=models.TextField(null=True),
        ),
    ]
