# Generated by Django 2.2.1 on 2019-07-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0010_auto_20190717_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DAQ',
            new_name='DAQServer',
        ),
    ]
