# Generated by Django 3.1.7 on 2021-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0012_auto_20210416_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='uri',
            field=models.CharField(default='localhost:10001', help_text='In the form of <em>host</em>:<em>path</em> where host is name or ip address and path is port number, device path, etc', max_length=100, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='interfacedef',
            name='type',
            field=models.CharField(choices=[('SerialPort', 'Serial'), ('TCPPort', 'TCP'), ('I2C', 'I2C'), ('A2D', 'A/D'), ('D2A', 'D/A'), ('GPIO', 'GPIO')], default='TCPPort', max_length=15),
        ),
    ]
