# Generated by Django 3.1.7 on 2021-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0013_auto_20210421_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAQServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='JSON Config')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='Options')),
            ],
            options={
                'verbose_name': 'DAQServerConfig',
                'verbose_name_plural': 'DAQServerConfigs',
            },
        ),
        migrations.AddField(
            model_name='daqserver',
            name='daq_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqserverconfig', verbose_name='DAQServer Config'),
        ),
    ]
