# Generated by Django 3.1.7 on 2021-04-30 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0014_auto_20210424_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daqserver',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='daqserver',
            name='port',
        ),
        migrations.AlterField(
            model_name='daqserver',
            name='host',
            field=models.CharField(default='localhost', help_text='hostname or ip address', max_length=30),
        ),
        migrations.AlterField(
            model_name='daqserver',
            name='name',
            field=models.CharField(default=uuid.uuid1, max_length=50),
        ),
    ]
