# Generated by Django 3.1.7 on 2021-04-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envinventory', '0001_initial'),
        ('envdaq', '0015_auto_20210430_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('controller_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.controllerdef', verbose_name='ControllerDef')),
            ],
            options={
                'verbose_name': 'controllercomponent',
                'verbose_name_plural': 'controllercomponents',
            },
        ),
        migrations.CreateModel(
            name='DAQController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('long_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Long Name')),
                ('measurement_sets', models.JSONField(blank=True, default=dict, verbose_name='Measurement Sets')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.controllercomponent', verbose_name='Component')),
                ('controller_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.controllerdef', verbose_name='Controller')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqserver', verbose_name='DAQ Server')),
            ],
            options={
                'verbose_name': 'DAQController',
                'verbose_name_plural': 'DAQControllers',
            },
        ),
        migrations.CreateModel(
            name='InstrumentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('controller_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.controllerdef', verbose_name='ControllerDef')),
            ],
            options={
                'verbose_name': 'instrumentcomponent',
                'verbose_name_plural': 'instrumentcomponents',
            },
        ),
        migrations.CreateModel(
            name='DAQInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('prefix', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefix')),
                ('long_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Long Name')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.instrumentcomponent', verbose_name='Component')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Controller')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envinventory.instrument', verbose_name='Instrument')),
            ],
            options={
                'verbose_name': 'daqinstrument',
                'verbose_name_plural': 'daqinstruments',
            },
        ),
    ]
