# Generated by Django 3.1.7 on 2021-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0016_controllercomponent_daqcontroller_daqinstrument_instrumentcomponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllercomponent',
            options={'verbose_name': 'Controller Component', 'verbose_name_plural': 'Controller Components'},
        ),
        migrations.AlterModelOptions(
            name='daqcontroller',
            options={'verbose_name': 'DAQ Controller', 'verbose_name_plural': 'DAQ Controllers'},
        ),
        migrations.AlterModelOptions(
            name='daqinstrument',
            options={'verbose_name': 'DAQ Instrument', 'verbose_name_plural': 'DAQ Instruments'},
        ),
        migrations.AlterModelOptions(
            name='instrumentcomponent',
            options={'verbose_name': 'Instrument Component', 'verbose_name_plural': 'Instrument Components'},
        ),
        migrations.RemoveField(
            model_name='controllercomponent',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='instrumentcomponent',
            name='primary',
        ),
        migrations.AddField(
            model_name='daqinstrument',
            name='primary_component',
            field=models.BooleanField(default=True, verbose_name='Primary component'),
        ),
    ]
