# Generated by Django 3.1.7 on 2021-05-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0017_auto_20210430_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqcontroller',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_components', to='envdaq.controllercomponent', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='daqcontroller',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daq_server', to='envdaq.daqserver', verbose_name='DAQ Server'),
        ),
        migrations.AlterField(
            model_name='daqinstrument',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_components', to='envdaq.instrumentcomponent', verbose_name='Component'),
        ),
        migrations.AlterField(
            model_name='daqinstrument',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daq_controller', to='envdaq.daqcontroller', verbose_name='Controller'),
        ),
    ]
