# Generated by Django 3.1.7 on 2021-05-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0019_auto_20210502_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqcontroller',
            name='namespace',
            field=models.CharField(default='<function uuid1 at 0x7fc9c0bd0f70>', max_length=100, verbose_name='Namespace'),
        ),
        migrations.AddField(
            model_name='daqcontroller',
            name='parent_controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Parent Controller'),
        ),
        migrations.AlterField(
            model_name='daqcontroller',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqserver', verbose_name='DAQ Server'),
        ),
    ]
