# Generated by Django 3.1.7 on 2021-05-03 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0020_auto_20210503_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqcontroller',
            name='namespace',
            field=models.CharField(default=uuid.uuid1, max_length=100, verbose_name='Namespace'),
        ),
    ]
