# Generated by Django 3.1.7 on 2021-05-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0022_auto_20210503_1606'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='daqcontroller',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('server__isnull', False), ('parent_controller__isnull', True)), models.Q(('server__isnull', True), ('parent_controller__isnull', False)), _connector='OR'), name='one_and_only_one_parent'),
        ),
    ]
