# Generated by Django 3.1.7 on 2021-05-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0023_auto_20210503_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daqcontroller',
            name='parent_controller',
            field=models.ForeignKey(blank=True, help_text='Must select either a Server or a Parent Controller', null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Parent Controller'),
        ),
        migrations.AlterField(
            model_name='daqcontroller',
            name='server',
            field=models.ForeignKey(blank=True, help_text='Must select either a Server or a Parent Controller', null=True, on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqserver', verbose_name='DAQ Server'),
        ),
    ]
