# Generated by Django 3.1.7 on 2021-05-03 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0024_auto_20210503_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqinstrument',
            name='namespace',
            field=models.CharField(default=uuid.uuid1, max_length=100, verbose_name='Namespace'),
        ),
    ]
