# Generated by Django 3.1.7 on 2021-05-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0025_daqinstrument_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqcontroller',
            name='prefix',
            field=models.CharField(default='default', max_length=30, verbose_name='Prefix'),
        ),
    ]
