# Generated by Django 3.1.7 on 2021-05-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0026_daqcontroller_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='default', max_length=100, verbose_name='Component Name')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqinstrument', verbose_name='Instrument')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.interface', verbose_name='Interface')),
            ],
            options={
                'verbose_name': 'Interface Component',
                'verbose_name_plural': 'Interface Components',
            },
        ),
    ]
