# Generated by Django 3.1.7 on 2021-05-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0027_interfacecomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcomponent',
            name='controller_def',
        ),
        migrations.RenameField(
            model_name='interfacecomponent',
            old_name='instrument',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='daqcontroller',
            name='component',
        ),
        migrations.RemoveField(
            model_name='daqinstrument',
            name='component',
        ),
        migrations.RemoveField(
            model_name='daqinstrument',
            name='primary_component',
        ),
        migrations.DeleteModel(
            name='ControllerComponent',
        ),
        migrations.DeleteModel(
            name='InstrumentComponent',
        ),
    ]
