# Generated by Django 3.1.7 on 2021-05-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0028_auto_20210517_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='default', max_length=100, verbose_name='Component Name')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.interface', verbose_name='Interface')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Parent Controller')),
            ],
            options={
                'verbose_name': 'Instrument Component',
                'verbose_name_plural': 'Instrument Components',
            },
        ),
        migrations.CreateModel(
            name='ControllerComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='default', max_length=100, verbose_name='Component Name')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.interface', verbose_name='Interface')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.daqcontroller', verbose_name='Parent Controller')),
            ],
            options={
                'verbose_name': 'Controller Component',
                'verbose_name_plural': 'Controller Components',
            },
        ),
    ]
