# Generated by Django 3.1.7 on 2021-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0029_controllercomponent_instrumentcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllercomponent',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary Component'),
        ),
        migrations.AddField(
            model_name='instrumentcomponent',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary Component'),
        ),
    ]
