# Generated by Django 3.1.7 on 2021-05-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0031_auto_20210517_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacecomponent',
            old_name='parent',
            new_name='instrument',
        ),
    ]
