# Generated by Django 3.1.7 on 2021-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0032_auto_20210517_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqserver',
            name='namespace2',
            field=models.JSONField(default=dict, verbose_name='NamespaceJSON'),
        ),
    ]
