# Generated by Django 3.1.7 on 2021-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0033_daqserver_namespace2'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqserver',
            name='autoenable',
            field=models.BooleanField(default=False, verbose_name='Auto Enable'),
        ),
    ]
