# Generated by Django 3.1.7 on 2021-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0037_daqcontroller_namespace2'),
    ]

    operations = [
        migrations.AddField(
            model_name='daqinstrument',
            name='measurement_sets',
            field=models.JSONField(blank=True, default=dict, verbose_name='Measurement Sets'),
        ),
    ]
