# Generated by Django 3.1.7 on 2021-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0038_daqinstrument_measurement_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacedef',
            name='type',
            field=models.CharField(choices=[('SerialPort', 'Serial'), ('TCPPort', 'TCP'), ('I2C', 'I2C'), ('A2D', 'A/D'), ('D2A', 'D/A'), ('GPIO', 'GPIO'), ('DUMMY', 'DUMMY')], default='TCPPort', max_length=15),
        ),
    ]
