# Generated by Django 2.1.4 on 2019-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('type_text', models.CharField(max_length=100)),
                ('mfg_text', models.CharField(max_length=100)),
                ('sn_text', models.CharField(max_length=100)),
                ('signature_text', models.CharField(max_length=200)),
            ],
        ),
    ]
