# Generated by Django 2.1.5 on 2019-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Controller type name', max_length=30)),
                ('_class', models.CharField(help_text='Enter class name', max_length=30)),
                ('_module', models.CharField(help_text='Enter module name', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
