# Generated by Django 2.1.5 on 2019-02-12 22:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0002_auto_20190212_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name for this controller', max_length=30)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name for this instrument', max_length=30)),
                ('uniqueID', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instrument type name', max_length=50)),
                ('model', models.CharField(help_text='Instrument type name', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='controllerdef',
            options={'verbose_name': 'Controller Definition', 'verbose_name_plural': 'Controller Definition'},
        ),
        migrations.AddField(
            model_name='instrument',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.InstrumentDef'),
        ),
        migrations.AddField(
            model_name='controller',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envdaq.ControllerDef'),
        ),
        migrations.AddField(
            model_name='controller',
            name='inst_list',
            field=models.ManyToManyField(help_text='Select insruments to control', to='envdaq.Instrument'),
        ),
    ]
