# Generated by Django 2.1.5 on 2019-02-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0003_auto_20190212_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='serial_number',
            field=models.CharField(default='1234', help_text='Enter serial number', max_length=30),
        ),
    ]
