# Generated by Django 2.1.5 on 2019-02-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0005_auto_20190214_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In use'), ('ON_LOAN', 'Out on loan'), ('MAINTENANCE', 'Out for maintenance')], default='MAINTENANCE', max_length=20),
        ),
    ]
