# Generated by Django 2.1.5 on 2019-02-15 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0006_instrument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('verbose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, help_text='Enter units using UDUnits convention', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='instrumentdef',
            name='id',
        ),
        migrations.RemoveField(
            model_name='instrumentdef',
            name='name',
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envdaq.Organization')),
            ],
            bases=('envdaq.organization',),
        ),
        migrations.AddField(
            model_name='person',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envdaq.Organization'),
        ),
        migrations.AddField(
            model_name='devicedef',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='envdaq.Person'),
        ),
        migrations.AddField(
            model_name='devicedef',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dev_mfg', to='envdaq.Organization'),
        ),
        migrations.AddField(
            model_name='devicedef',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev_owner', to='envdaq.Organization'),
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='devicedef_ptr',
            field=models.OneToOneField(auto_created=True, default='tmp', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='envdaq.DeviceDef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumentdef',
            name='measurements',
            field=models.ManyToManyField(to='envdaq.Measurement'),
        ),
    ]
