# Generated by Django 2.1.5 on 2019-02-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envdaq', '0008_auto_20190215_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedef',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='devicedef',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='affiliation',
        ),
    ]
